# Generated by Django 4.2.5 on 2023-10-04 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=13)),
                ('cv', models.FileField(upload_to='cv/')),
                ('cl', models.FileField(upload_to='cl/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='Full Time', max_length=15)),
                ('work_type', models.CharField(choices=[('Remote', 'Remote'), ('Hybrid', ' Hybrid'), ('On-Stie', 'On-Stie')], default='Remote', max_length=15)),
                ('job_location', models.CharField(max_length=200)),
                ('job_salary', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(8)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='newjob_images/')),
                ('company_name', models.CharField(max_length=200)),
                ('company_link', models.URLField(blank=True, null=True)),
                ('job_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
