# Generated by Django 4.2.5 on 2023-10-04 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='JobCategory',
        ),
    ]
