# Generated by Django 4.2.5 on 2023-10-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_category_jobcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newjob',
            name='image',
            field=models.ImageField(default='job_default_img.jpg', upload_to='newjob_images/'),
        ),
    ]
