# Generated by Django 4.2.5 on 2023-10-05 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_newjob_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newjob',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcategory'),
        ),
    ]
