# Generated by Django 4.2.5 on 2023-10-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_newjob_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newjob',
            name='job_description',
            field=models.TextField(default='ddddddddddddddddddddddddddddddddd'),
            preserve_default=False,
        ),
    ]
