# Generated by Django 4.2.5 on 2023-10-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newjob_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newjob',
            name='responsibility',
            field=models.TextField(default='eeeeeeeeeeeeeeeeeeeeeeeeeeee'),
            preserve_default=False,
        ),
    ]
