# Generated by Django 4.2.5 on 2023-10-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newjob_responsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='newjob',
            name='qualifications',
            field=models.TextField(default='qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq'),
            preserve_default=False,
        ),
    ]
