# Generated by Django 4.2.5 on 2023-10-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_contact_us_contact_alter_newjob_about_company_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_Details',
            new_name='Employee_Detail',
        ),
        migrations.RenameModel(
            old_name='NewJob',
            new_name='Job',
        ),
    ]
