# Generated by Django 4.2.5 on 2023-10-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_employee_details_employee_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(default='avatar.png', upload_to='comments_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
