# Generated by Django 4.2.5 on 2023-10-09 11:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_comment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='about_company',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
