# Generated by Django 4.2.5 on 2023-10-09 11:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_job_about_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibility',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
