# Generated by Django 4.2.5 on 2023-10-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_job_job_description_alter_job_qualifications_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_detail',
            old_name='portfolio_link',
            new_name='linkedin_link',
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(),
        ),
    ]
