# Generated by Django 4.2.5 on 2023-10-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_portfolio_link_employee_detail_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to='comments_images/'),
        ),
    ]
